project_id = "mucojbkzmpmkcivoxrze"

[functions.run-cloud-actions-v2]
verify_jwt = false

[functions.cloud-action-orchestrator]  
verify_jwt = false

[functions.cloud-action-steps]
verify_jwt = false

[functions.keep-alive-heartbeat]
verify_jwt = false

[functions.refresh-mendix-environment-status]
verify_jwt = false

[functions.send-email-mandrill]
verify_jwt = false

[functions.monitor-environment-logs]
verify_jwt = false

[functions.download-mendix-logs]
verify_jwt = false

[functions.process-log-monitoring]
verify_jwt = false

[functions.owasp-check-endpoint-restdoc]
verify_jwt = false
