project_id = "mucojbkzmpmkcivoxrze"

[functions.run-cloud-actions-v2]
verify_jwt = false

[functions.cloud-action-orchestrator]  
verify_jwt = false

[functions.cloud-action-steps]
verify_jwt = false

[functions.keep-alive-heartbeat]
verify_jwt = false
