project_id = "uiquvncvmimhbkylfzzp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54329

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[functions]
enabled = true

[functions.fetch-mendix-apps]

[functions.start-mendix-environment]

[functions.stop-mendix-environment]

[functions.download-mendix-logs]