// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rewepsqarjbdjvfyuvnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJld2Vwc3FhcmpiZGp2Znl1dm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTg2MDQsImV4cCI6MjA3Mjk5NDYwNH0.n0z--IY9zhE1PUV6PZ4iqmZCMUnMDSKSoe426tAwsiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});